name: reactjs CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix: 
        node-version: [ 20.x]
        operating-system: [ self-hosted ]
    runs-on: ${{  matrix.operating-system}}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{  matrix.node-version }}
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: Run build
        run: npm run build --if-present
      - name: clear contents of var/www/html/*
        run: sudo rm -rf /var/www/html/*
      - name: copy dist file
        run: sudo cp -r dist/* /var/www/html